# Generated by Django 2.2 on 2020-03-15 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_confirmstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default='none')),
                ('c_time', models.DateTimeField(default=datetime.date.today, verbose_name='日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.User')),
                ('type', models.ForeignKey(default='无', on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Text_type')),
            ],
        ),
    ]
